services:
  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local-645
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
