services:
  trail:
    image: docker.io/trailbase/trailbase:latest
    # build: .
    # ports:
    #   - "${PORT:-4000}:4000"
    restart: unless-stopped
    user: "root:root"
    volumes:
      - '${DATA_DIR:-.}/traildepot:/app/traildepot'
    environment:
      - SERVICE_FQDN_645_LIVE_TRAILBASE
      # Override the default env-logger.
      # RUST_LOG: "info,refinery_core=warn"
      - RUST_BACKTRACE='1'
    command: '/app/trail --data-dir /app/traildepot run --address 0.0.0.0:4000 --dev'